- azure-pipelines.yml
- generate-wiki-docs.yml
> AB#6 Generate release notes for each environment

- azure-pipelines.yml
- generate-wiki-docs.yml
There was an error on Handlebars template. fixed the error.
> fix (AB#14): Handlebars error fix

- azure-pipelines.yml
- build-handlebars-template.md
- generate-wiki-docs.yml
added template file for handlebar templates and moved git release task to build stage.
> feat (AB#16): Templatefile

- README.md
- azure-pipelines.yml
- build-handlebars-template-detailed.md
- build-handlebars-template.md
This PR contains two work items and two bug fixes.
Card details: 
https://dev.azure.com/HassanAbbasShahSoftLTD/Deployment%20Approvals%20Demo/_workitems/edit/17
https://dev.azure.com/HassanAbbasShahSoftLTD/Deployment%20Approvals%20Demo/_workitems/edit/18
https://dev.azure.com/HassanAbbasShahSoftLTD/Deployment%20Approvals%20Demo/_workitems/edit/19
https://dev.azure.com/HassanAbbasShahSoftLTD/Deployment%20Approvals%20Demo/_workitems/edit/20
> feat (AB#17): Test pr

- azure-pipelines.yml
> feat (AB#17): testing tag and bumped up version v1.11.21

- azure-pipelines.yml
> AB#17 pr condition updated

- azure-pipelines.yml
> fix (AB#18) fixing git tage name 

- azure-pipelines.yml
> fix (AB#20): bumping up version v1.11.24

- azure-pipelines.yml
> fix (AB#19): fixed handelbar template v1.11.25

- azure-pipelines.yml
> fix (AB#19 - fixed git tag push)

- azure-pipelines.yml
> AB#18 bumped up version

- azure-pipelines.yml
> AB# 19 fix #$(GitVersion.NugetVersionV2)

- azure-pipelines.yml
> fix (AB#19): removed git tag creation v1.11.31

- azure-pipelines.yml
> feat (AB#21) - Create Git Hub release only on PR v1.11.32

- azure-pipelines.yml
> AB#19 bumping the version v1.11.33

- azure-pipelines.yml
> AB #19 Creategitdepth

- azure-pipelines.yml
> AB# 19 vfgdsfg

- azure-pipelines.yml
> feat (AB#21): gitfemo

- README.md
- azure-pipelines.yml
> feat (AB#24): TestPBI1 commit

- azure-pipelines.yml
> fix (AB#25): Testbug1

- azure-pipelines.yml
> feat (AB#21): create Git release on PR

- azure-pipelines.yml
> fix (AB#26) bumped up the version to 43
